const appname = "Laza";
const appversion = "Version 1.0.0";
const credits = "@Ameer Hamza";
const mnbtns = "Men";
const wbtns = "Women";
const emailftitle = "Email Address";
const usernameftitle = "Username";
const passwordftitle = "Password";
const forgotpass = "Forgot Password";
